# File: .github/workflows/ci.yml
name: Build AMI with Packer

on:
  push:
    branches: 
      - main
    paths:
      - "project2/**"  
  pull_request:
    branches:
      - main
    paths:
      - "project2/**"

jobs:
  packer:
    name: Run Packer Build
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.12.0'  # Use the version you want for packer

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate initilize template
        run: packer init ./project2/aws-ubuntu.pkr.hcl

      - name: Validate Packer template
        run: packer validate ./project2/aws-ubuntu.pkr.hcl

      - name: Build AMI with Packer
        run: packer build ./project2/aws-ubuntu.pkr.hcl

